blank_issues_enabled: false
contact_links:
  - name: WinDurango Troubleshooting/Support 
    url: https://discord.gg/dHdteazP
    about: For support and technical issues, please come to our Discord server.
